name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  changed-files:  # id of input
    description: 'List of changed files'
    required: false
    default: ''
  added-files:  # id of input
    description: 'List of added files'
    required: false
    default: ''
  renamed-files:  # id of input
    description: 'List of renamed files'
    required: false
    default: ''
outputs:
  files-to-deploy: # id of output
    description: 'List of changed Salesforce files'
runs:
  using: 'node12'
  main: 'index.js'